# Generated by Django 3.0.6 on 2020-05-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100)),
                ('number_seasons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('season_number', models.IntegerField(primary_key=True, serialize=False)),
                ('episodes', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomgen.Series', verbose_name='series of the season')),
            ],
        ),
    ]
